-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --


-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")

hl.on("hyprland.start", function()
  hl.exec_cmd("noctalia")
end)


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
-- Keep this generic rule as a fallback for displays not present in the
-- configuration generated by nwg-displays.
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})

-- nwg-displays regenerates this file and reloads Hyprland when settings are applied.
-- También lo genera otra herramienta (nwg-displays), así que va con pcall por
-- el mismo motivo que 'noctalia': que falte no puede abortar la config.
if not pcall(require, "monitors") then
  print("[hyprland] no encontré monitors.lua; revisá ~/.config/hypr/monitors.conf")
end


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "kitty"
local fileManager = (os.getenv("HOME") or "") .. "/.local/bin/dolphin"
local ipc = "noctalia msg "
local browser = "firefox"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
-- hl.on("hyprland.start", function () 
--   hl.exec_cmd(terminal)
--   hl.exec_cmd("nm-applet")
--   hl.exec_cmd("waybar & hyprpaper & firefox")
-- end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_THEME", "Vimix-white-cursors")
hl.env("XCURSOR_SIZE", "26")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
-- NOTA: no se tocaron colores, bordes ni blur — se dejaron exactamente como estaban.
hl.config({
    general = {
        gaps_in  = 4,
        gaps_out = 10,

        border_size = 2,

        col = {
            active_border   = { colors = {"rgba(33ccffee)", "rgba(00ff99ee)"}, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        -- Rounding más generoso: las esquinas "burbuja" son una de las señas
        -- de identidad del look Aero/glass (nada de esquinas casi rectas).
        rounding       = 16,
        rounding_power = 2.4,

        -- Se mantienen los valores de opacidad que ya tenías.
        active_opacity   = 0.9,
        inactive_opacity = 0.8,

        -- Sombra un poco más suave y difusa: en vez de una sombra "dura"
        -- de tema oscuro moderno, buscamos el halo suave típico de Aero.
        shadow = {
            enabled      = true,
            range        = 18,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        -- Blur más pesado y con más "passes": es lo que hace el trabajo
        -- pesado del efecto vidrio esmerilado. contrast/brightness altos
        -- imitan el brillo sobre-expuesto típico del glass de Vista/7;
        -- noise le da grano fino para que no se vea un blur plano.
        blur = {
            enabled            = true,
            size               = 8,
            passes             = 4,
            vibrancy           = 0.1696,
            contrast           = 1.2,
            brightness         = 1.15,
            noise              = 0.02,
            new_optimizations  = true,
            xray               = true,
            ignore_opacity     = true,
            popups             = true, -- menús/tooltips también con vidrio
        },
    },

    animations = {
        enabled = true,
    },
})

-- ==========================================================================
--  ANIMACIONES — ESTILO "PUNK-AERO"
--  Golpes rápidos con overshoot y resortes elásticos para una sensación viva.
--  Nada de esto toca colores, bordes ni blur: es pura coreografía de movimiento.
-- ==========================================================================

-- Curvas Bezier "punk": entrada agresiva con overshoot (rebasa y vuelve).
hl.curve("punkSnap",     { type = "bezier", points = { {0.83, 0}, {0.17, 1.15} } }) -- golpe seco con rebote
hl.curve("punkKick",     { type = "bezier", points = { {0.9, -0.35}, {0.1, 1.5} } }) -- patada: anticipación + overshoot fuerte
hl.curve("punkSlam",     { type = "bezier", points = { {0.95, 0.05}, {0.05, 0.95} } }) -- cierre tipo portazo, casi instantáneo
hl.curve("aeroSwing",    { type = "bezier", points = { {0.36, 1.4}, {0.64, -0.4} } })

-- Resortes elásticos con más oscilación
-- que el resorte por defecto (más stiffness = más rápido, menos dampening = más rebote).
hl.curve("aeroSpring",    { type = "spring", mass = 0.65, stiffness = 260, dampening = 14 })
hl.curve("punkSpring",    { type = "spring", mass = 0.65,  stiffness = 340, dampening = 11 })

-- Curvas base originales, se mantienen por si algo las referencia.
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 })

-- Velocidades altas con resortes elásticos.
hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 9,    bezier = "punkSnap" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 7.5,  spring = "aeroSpring" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 7,    spring = "punkSpring",    style = "popin 70%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 3.2,  bezier = "punkSlam",       style = "popin 75%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 4.5,  bezier = "punkSnap" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 3.8,  bezier = "punkSlam" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 6,    bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 7,    bezier = "punkSnap" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 7.5,  spring = "aeroSpring", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 3.5,  bezier = "punkSlam",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 4.2,  bezier = "punkSnap" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 3.5,  bezier = "punkSlam" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 4.6,  bezier = "aeroSwing",  style = "slidevert" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 3.6,  spring = "aeroSpring", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 3.6,  bezier = "punkSlam",       style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 9,    bezier = "punkKick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = false, -- If true disables the random hyprland logo / anime girl background. :(
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + SHIFT + RETURN", hl.dsp.exec_cmd(terminal, { float = true, size = {800, 500}, center = true }))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(browser))
local closeWindowBind = hl.bind(mainMod .. " + Q", hl.dsp.window.close())
-- closeWindowBind:set_enabled(false)
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))    -- dwindle only
-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

--Noctalia
hl.bind("ALT + Tab", hl.dsp.exec_cmd(ipc .. "window-switcher"))
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd(ipc .. "panel-toggle launcher"))
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd(ipc .. "panel-toggle control-center"))
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd(ipc .. "panel-toggle yuuto/calculator:panel"))
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd(ipc .. "session lock"))
--Screenshot
hl.bind("PRINT", hl.dsp.exec_cmd(ipc .. "screenshot-fullscreen"))
hl.bind("SHIFT + PRINT", hl.dsp.exec_cmd(ipc .. "screenshot-annotate"))


-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end


-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })



-- Core binds

hl.bind("ALT + Tab", hl.dsp.exec_cmd(ipc .. "window-switcher"))

-- Media keys
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd(ipc .. "volume-up"))
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd(ipc .. "volume-down"))
hl.bind("XF86AudioMute", hl.dsp.exec_cmd(ipc .. "volume-mute"))
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd(ipc .. "brightness-up"))
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd(ipc .. "brightness-down"))


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

hl.layer_rule({
  name = "noctalia",
  match = {
    namespace = "^noctalia-(bar-.+|notification|dock|panel|attached-panel|osd|window-switcher)$",
  },
  no_anim = true,
  ignore_alpha = 0.5,
  blur = true,
  blur_popups = true,
  xray = true, -- deja que el blur "vea" lo que hay detrás del panel, más vidrio real
})

-- Ventanas flotantes chicas (diálogos, popups): rounding un poco mayor
-- para que combinen con el resto. El blur ya las cubre automáticamente
-- vía el bloque global de "decoration" — no existe un campo "blur" a
-- nivel de window_rule en Hyprland (eso sí existe en layer_rule).
hl.window_rule({
    name  = "glass-floating-dialogs",
    match = { float = true },

    rounding = 16,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})


-- For Noctalia Color templates
--
-- OJO: noctalia.lua NO es config, lo GENERA Noctalia (dice "Generated by
-- Noctalia" en la primera línea). Con require pelado, si el archivo no está
-- Hyprland aborta la carga de toda la config y te deja medio escritorio con
-- un error en la última línea. Como es opcional de verdad, que falte solo
-- significa que no se aplica la paleta de colores.
--
-- Y no solo el require: también la llamada. apply_theme() hace un hl.config()
-- con los colores que generó Noctalia, y si Hyprland no acepta alguno (nueva
-- nueva, clave cambiada, color con sintaxis no soportada) el error salta DENTRO
-- de la llamada y se reporta en esta línea. Un archivo generado y cosmético no
-- puede tirar abajo la config.
local _ok, _noctalia = pcall(require, "noctalia")
if not _ok then
  print("[hyprland] no encontré el módulo 'noctalia' (lo genera Noctalia); sigo sin su paleta")
elseif type(_noctalia) ~= "table" or type(_noctalia.apply_theme) ~= "function" then
  print("[hyprland] el módulo 'noctalia' no trae apply_theme; lo salto")
else
  local _applied, _why = pcall(_noctalia.apply_theme)
  if not _applied then
    print("[hyprland] apply_theme() falló: " .. tostring(_why))
    print("[hyprland] el resto de la config está bien; solo falta la paleta de Noctalia")
  end
end