-- Generated by Noctalia

local primary = "rgb(d0ffbe)"
local surface = "rgb(0c1609)"
local on_surface = "rgb(dae6d0)"
local secondary = "rgb(6fdf59)"
local on_secondary = "rgb(023a00)"
local err_color = "rgb(ffb4ab)"  -- NO llamarse "error": tapa la global de Lua
local on_error = "rgb(690005)"

local function apply_theme()
    hl.config({
        general = {
            col = {
                active_border = primary,
                inactive_border = surface,
            },
        },
        group = {
            col = {
                border_active = secondary,
                border_inactive = surface,
                border_locked_active = err_color,
                border_locked_inactive = surface,
            },

            groupbar = {
                col = {
                    active = secondary,
                    inactive = surface,
                    locked_active = err_color,
                    locked_inactive = surface,
                },
                text_color = on_secondary,
                text_color_inactive = on_surface,
                text_color_locked_active = on_error,
                text_color_locked_inactive = on_surface,
            },
        },
    })
end

return {
    colors = {
        primary = primary,
        surface = surface,
        on_surface = on_surface,
        secondary = secondary,
        on_secondary = on_secondary,
        error = err_color,
        on_error = on_error,
    },
    apply_theme = apply_theme
}
